### ISSUE TITLE
tree -J output doesn't work with default configuration

### ISSUE THREAD

**Issue by ricka** [electerious/fsify#38]
Trying to use this utility with `tree -J` output and I can't see how it would ever work.

1. `tree -j` output seems to have the current working directory in it's output with name ".". This causes an exception to be thrown in line 27 of parseEntry

```
UnhandledPromiseRejectionWarning: Error: Entry name points to the same path as the surrounding structure
    at /Users/ricka/code/rhi/sfdc-diff-deploy/node_modules/fsify/src/parseEntry.js:27:10
```

I believe that error will always happen if "." is in the output.

2. Additionally, there is an entry near the end of my tree output that shows a report, something like this:
```json
{"type":"report","directories":31,"files":276}
```
I believe this will also cause an error to be thrown as the `get` method seems to only want files or directories.

If I manually remove these from tree output, I'm able to get this utility to work, but would like to see it work with default tree output.

**Comment by electerious** [comment]
Thanks for letting me know 😊 I've fixed the example: https://github.com/electerious/fsify#structure-from-tree
